main: me.meerkat.towers.Towers
version: 1.8.0
api-version: 1.16
name: Towers
author: PablockDA
depend: [Vault]
loadbefore: [Vault]
commands:
  towers: 
    aliases: [tw]
    description: Towers main command